FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_pm
FEATURES_REQUIRED += periph_rtc

ifeq (,$(filter samr34,$(CPU_MODEL)))
  USEMODULE += sx127x
  USEMODULE += periph_spi_reconfigure
endif
