ifneq (,$(filter periph_i2c,$(USEMODULE)))
    USEMODULE += ztimer
    USEMODULE += ztimer_msec
    USEMODULE += shell_cmd_i2c_scan
endif

ifneq (,$(filter fram,$(USEMODULE)))
    USEMODULE += od
endif

