USEMODULE += periph_gpio
USEMODULE += periph_i2c
USEMODULE += periph_i2c_reconfigure
USEMODULE += ztimer
USEMODULE += fram

USEMODULE += ps
USEMODULE += periph_pm
USEMODULE += saul_reg
USEMODULE += shell_cmd_i2c_scan
