# include variants of the BME68X drivers as pseudo modules
PSEUDOMODULES += bme68x_i2c
PSEUDOMODULES += bme68x_spi
PSEUDOMODULES += bme68x_fp

USEMODULE_INCLUDES_bme68x := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_bme68x)
