ifneq (,$(filter periph_i2c,$(USEMODULE)))
  USEMODULE += periph_i2c_reconfigure
endif

ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += sx1276
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif
