USEMODULE += periph_i2c
USEMODULE += periph_i2c_reconfigure

ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += sx1276
endif

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += saul_gpio
endif
